name: Debug via docker

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
      timeout-minutes: 30